import "@cloudcannon/editable-regions/astro-react-renderer";
import "@cloudcannon/editable-regions/astro-svelte-renderer";
import "@cloudcannon/editable-regions/astro-vue-renderer";

import { registerAstroComponent } from "@cloudcannon/editable-regions/astro";
import { registerReactComponent } from "@cloudcannon/editable-regions/react";
import { registerSvelteComponent } from "@cloudcannon/editable-regions/svelte";
import { registerVueComponent } from "@cloudcannon/editable-regions/vue";

import ReactTest from "./src/components/react-test.astro";
import ReactTestInner from "./src/components/react-test-inner";
import SlotTest from "./src/components/slot-test.astro";
import AstroTest from "./src/components/astro-test.astro";
import TransitionBox from "./src/components/transition-box.astro";
import AssetsBox from "./src/components/assets-box.astro";
import ContentCard from "./src/components/content-card.astro";
import I18nLink from "./src/components/i18n-link.astro";
import ActionsButton from "./src/components/actions-button.astro";
import MiddlewareInfo from "./src/components/middleware-info.astro";
import EnvDisplay from "./src/components/env-display.astro";
import SvelteTest from "./src/components/svelte-test.astro";
import SvelteCounter from "./src/components/svelte-counter.svelte";
import SvelteStatic from "./src/components/svelte-static.svelte";
import VueTest from "./src/components/vue-test.astro";
import VueCounter from "./src/components/vue-counter.vue";
import VueStatic from "./src/components/vue-static.vue";

registerAstroComponent("astro-test", AstroTest);
registerAstroComponent("slot-test", SlotTest);
registerAstroComponent("react-test", ReactTest);
registerAstroComponent("transition-box", TransitionBox);
registerAstroComponent("assets-box", AssetsBox);
registerAstroComponent("content-card", ContentCard);
registerAstroComponent("i18n-link", I18nLink);
registerAstroComponent("actions-button", ActionsButton);
registerAstroComponent("middleware-info", MiddlewareInfo);
registerAstroComponent("env-display", EnvDisplay);
registerReactComponent("react-test-inner", ReactTestInner);
registerAstroComponent("svelte-test", SvelteTest);
registerSvelteComponent("svelte-counter", SvelteCounter);
registerSvelteComponent("svelte-static", SvelteStatic);
registerAstroComponent("vue-test", VueTest);
registerVueComponent("vue-counter", VueCounter);
registerVueComponent("vue-static", VueStatic);
