import "@cloudcannon/editable-regions/astro-react-renderer";
import "@cloudcannon/editable-regions/astro-svelte-renderer";
import "@cloudcannon/editable-regions/astro-vue-renderer";

import { registerAstroComponent } from "@cloudcannon/editable-regions/astro";

import ActionsTest from "./src/components/actions-test.astro";
import AssetsGetImage from "./src/components/assets-get-image.astro";
import AssetsImage from "./src/components/assets-image.astro";
import AssetsPicture from "./src/components/assets-picture.astro";
import CollectionList from "./src/components/collection-list.astro";
import EnvDisplay from "./src/components/env-display.astro";
import I18nTest from "./src/components/i18n-test.astro";
import MiddlewareTest from "./src/components/middleware-test.astro";
import ReactCounter from "./src/components/react-counter.astro";
import ReactSlotted from "./src/components/react-slotted.astro";
import ReactStatic from "./src/components/react-static.astro";
import SlotParent from "./src/components/slot-parent.astro";
import Static from "./src/components/static.astro";
import SvelteCounter from "./src/components/svelte-counter.astro";
import SvelteSlotted from "./src/components/svelte-slotted.astro";
import SvelteStatic from "./src/components/svelte-static.astro";
import TransitionsTest from "./src/components/transitions-test.astro";
import VueCounter from "./src/components/vue-counter.astro";
import VueCounterIdle from "./src/components/vue-counter-idle.astro";
import VueCounterVisible from "./src/components/vue-counter-visible.astro";
import VueSlotted from "./src/components/vue-slotted.astro";
import VueStatic from "./src/components/vue-static.astro";
import WithProps from "./src/components/with-props.astro";
import WithSlot from "./src/components/with-slot.astro";

registerAstroComponent("astro-static", Static);
registerAstroComponent("astro-props", WithProps);
registerAstroComponent("astro-slot", WithSlot);
registerAstroComponent("astro-slot-parent", SlotParent);
registerAstroComponent("astro-collection", CollectionList);
registerAstroComponent("astro-env", EnvDisplay);
registerAstroComponent("astro-assets-image", AssetsImage);
registerAstroComponent("astro-assets-get-image", AssetsGetImage);
registerAstroComponent("astro-assets-picture", AssetsPicture);
registerAstroComponent("astro-actions", ActionsTest);
registerAstroComponent("astro-i18n", I18nTest);
registerAstroComponent("astro-middleware", MiddlewareTest);
registerAstroComponent("astro-transitions", TransitionsTest);
registerAstroComponent("astro-vue-static", VueStatic);
registerAstroComponent("astro-vue-counter", VueCounter);
registerAstroComponent("astro-vue-counter-idle", VueCounterIdle);
registerAstroComponent("astro-vue-counter-visible", VueCounterVisible);
registerAstroComponent("astro-vue-slotted", VueSlotted);
registerAstroComponent("astro-react-static", ReactStatic);
registerAstroComponent("astro-react-counter", ReactCounter);
registerAstroComponent("astro-react-slotted", ReactSlotted);
registerAstroComponent("astro-svelte-static", SvelteStatic);
registerAstroComponent("astro-svelte-counter", SvelteCounter);
registerAstroComponent("astro-svelte-slotted", SvelteSlotted);
